[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm -w apps/api run build"

[deploy]
startCommand = "npm -w apps/api run prisma:migrate:deploy && npm -w apps/api run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

